openapi: 3.0.0
info:
  title: Patent API
  description: API for retrieving patent data
  version: 1.0.0

servers:
  # When deploying to production, replace the URL with the actual production URL
  - url: https://api.findthegem.com/v1

paths:
  /v1/patents:
    get:
      summary: Retrieve a list of patents with the most relevant information
      description: Returns a paginated list of patent overviews
      responses:
        '200':
          $ref: '#/components/responses/PatentOverviewList'
        '400':
            description: Invalid request

components:
  schemas:
    patentOverview:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the patent
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          description: Title of the patent
          example: "Interlaced multiband antenna arrays"
        expirationDate:
          type: string
          format: date
          description: Patent expiration date
          example: "2025-12-31"
        patentCountry:
          type: string
          description: Country where the patent has been issued
          example: "US"
        sizePatentFamily:
          type: integer
          description: The number of patents within the same patent family
          example: 5
        numberCitations:
          type: integer
          description: Number of times the patent has been cited
          example: 10
        status:
          type: string
          description: Current status of the patent (e.g., active, expired, pending)
          example: "active"
        punctuation:
          type: number
          format: float
          minimum: 0
          maximum: 10
          description: A score or rating assigned to the patent (0-10 scale)
          example: 7.5
        applicationFields:
          type: array
          items:
            type: string
          description: List of fields or industries where the patent applies
          example: ["Technology", "Healthcare", "Automotive"]
  responses:
    PatentOverviewList:
      description: Successful retrieval of patents
      content:
        application/json:
          schema:
            type: object
            properties:
              number:
                type: integer
                description: The total number of patents returned
              results:
                type: array
                items:  # Schema for each patent overview item
                  $ref: '#/components/schemas/patentOverview'
          examples:
            example1:
              value:
                number: 2,
                results: [
                  {
                    "id": "123e4567-e89b-12d3-a456-426614174000",
                    "title": "Interlaced multiband antenna arrays",
                    "expirationDate": "2025-12-31",
                    "patentCountry": "US",
                    "sizePatentFamily": 5,
                    "numberCitations": 10,
                    "status": "active",
                    "punctuation": 7.5,
                    "applicationFields": ["Technology", "Healthcare", "Automotive"]
                  },
                  {
                    "id": "789e4567-e89b-12d3-a456-426614174000",
                    "title": "Another Innovative Patent Title",
                    "expirationDate": "2026-12-31",
                    "patentCountry": "UK",
                    "sizePatentFamily": 3,
                    "numberCitations": 8,
                    "status": "pending",
                    "punctuation": 8.5,
                    "applicationFields": ["Technology", "Education"]
                  }
                ]